title: My Site
# Remove 'theme' and 'remote_theme' entirely to test
# This uses the 'Architect' theme which is built into GitHub
theme: jekyll-theme-architect

plugins:
  - jekyll-remote-theme

# This helps avoid 'file not found' errors
sass:
  style: compressed
  
